### ISSUE TITLE
How to setup google signup on React-Native

### ISSUE THREAD

**Issue by Super0109** [Super0109/Cookie#1]
Now, I am doing google signin on React-Native.
But not working well.
Please help me in this problem.

Thanks in advance.

**Comment by SuperSmile0109** [comment]
You can create the OauthCLientID first on the https://console.cloud.google.com/apis.credentials
Reference urls:
https://stackoverflow.com/questions/47437678/why-do-i-get-com-google-android-gms-common-api-apiexception-10
And then create the sha-1 using keystore file (required the keystore file about the current app)
can generate the sha-1 using this command "keytool -keystore key0.jks -list -v" using cmd

It will helpful for you.

Best regards

**Comment by Super0109** [comment]
Okay, thanks
